module.exports = {
	RECEIVE_CATEGORIES: 'RECEIVE_CATEGORIES',
	SEARCH_RESULTS: 'SEARCH_RESULTS',
	RECEIVE_RESULTS: 'RECEIVE_RESULTS',
	MENU_CHOICE: 'MENU_CHOICE',
	RECEIVE_ITEM: 'RECEIVE_ITEM',
	RECEIVE_TRACK: 'RECEIVE_TRACK',
	GET_ITEM: 'GET_ITEM',
	GET_TRACK: 'GET_TRACK'
}